apiVersion: v1
data:
  host: MTI3LjAuMC4xOjMwMDAx
  useremail: ""
  username: YWRtaW4=
  userpassword: YWNjb3JkaW9uYWRtaW4=
kind: Secret
metadata:
  labels:
    a7n/task: a7n-docker-registry
  name: accordion-docker-registry
type: a7n-docker-registry
